
FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends tzdata && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pandas sqlalchemy psycopg2-binary python-dotenv

WORKDIR /app
COPY csv_to_postgres.py /app/csv_to_postgres.py
