
version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: pg_csv
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file: [.env]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 12
    volumes:
      - pgdata:/var/lib/postgresql/data

  csv_loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    env_file: [.env]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${CSV_DIR:-./data}:/app/data:ro
    command: ["python", "/app/csv_to_postgres.py"]
    restart: "no"

volumes:
  pgdata:
